export const cartActionTypes = {
    TOGGLE_CART_HIDDEN : "TOGGLE_CART_HIDDEN" , 
    ADD_ITEM:"ADD_ITEM",
    DECREASE_AND_REMOVE_ITEM: 'DECREASE_AND_REMOVE_ITEM',
    REMOVE_ITEM_TO_CART : "REMOVE_ITEM_TO_CART"
}